'===== libraries ====='
library(igraph)

source("EuNames.R")

'===== functions definition ====='
'Europe Graph'
EuGraph <- function() {
  #Noms des Pays
  Names = EuNames()
  L = length(Names)
  
  #création d'un graph vide
  g_eu <- graph.empty()
  #ajout de 36 nodes
  g_eu <- add.vertices(g_eu, L)
  #nommage des nodes
  V(g_eu)$name <- Names[1:L]
  #ajout des liens
  g_eu <- g_eu + edge("Finland","Norway")
  g_eu <- g_eu + edge("Finland","Sweden")
  g_eu <- g_eu + edge("Finland","Russia")
  g_eu <- g_eu + edge("Russia","Sweden")
  g_eu <- g_eu + edge("Norway","Sweden")
  g_eu <- g_eu + edge("Denmark","Sweden")
  g_eu <- g_eu + edge("Norway","Denmark")
  g_eu <- g_eu + edge("Germany","Denmark")
  g_eu <- g_eu + edge("Germany","Netherlands")
  g_eu <- g_eu + edge("Germany","Belgium")
  g_eu <- g_eu + edge("Germany","France")
  g_eu <- g_eu + edge("Germany","Switzerland")
  g_eu <- g_eu + edge("Germany","Austria")
  g_eu <- g_eu + edge("Germany","Czech Republic")
  g_eu <- g_eu + edge("Germany","Poland")
  g_eu <- g_eu + edge("Netherlands","Belgium")
  g_eu <- g_eu + edge("Belgium","France")
  g_eu <- g_eu + edge("Ireland","United Kingdom")
  g_eu <- g_eu + edge("United Kingdom","France")
  g_eu <- g_eu + edge("Portugal","Spain")
  g_eu <- g_eu + edge("Spain","France")
  g_eu <- g_eu + edge("Italy","France")
  g_eu <- g_eu + edge("Switzerland","France")
  g_eu <- g_eu + edge("Switzerland","Italy")
  g_eu <- g_eu + edge("Estonia","Latvia")
  g_eu <- g_eu + edge("Estonia","Russia")
  g_eu <- g_eu + edge("Lithuania","Latvia")
  g_eu <- g_eu + edge("Latvia","Russia")
  g_eu <- g_eu + edge("Lithuania","Poland")
  g_eu <- g_eu + edge("Belaruss","Latvia")
  g_eu <- g_eu + edge("Belaruss","Russia")
  g_eu <- g_eu + edge("Belaruss","Poland")
  g_eu <- g_eu + edge("Belaruss","Lithuania")
  g_eu <- g_eu + edge("Belaruss","Ukraine")
  g_eu <- g_eu + edge("Russia","Ukraine")
  g_eu <- g_eu + edge("Poland","Ukraine")
  g_eu <- g_eu + edge("Poland","Slovakia")
  g_eu <- g_eu + edge("Ukraine","Slovakia")
  g_eu <- g_eu + edge("Poland","Czech Republic")
  g_eu <- g_eu + edge("Slovakia","Czech Republic")
  g_eu <- g_eu + edge("Austria","Czech Republic")
  g_eu <- g_eu + edge("Austria","Slovakia")
  g_eu <- g_eu + edge("Austria","Switzerland")
  g_eu <- g_eu + edge("Austria","Italy")
  g_eu <- g_eu + edge("Austria","Slovenia")
  g_eu <- g_eu + edge("Slovenia","Italy")
  g_eu <- g_eu + edge("Hungary","Austria")
  g_eu <- g_eu + edge("Hungary","Slovakia")
  g_eu <- g_eu + edge("Hungary","Ukraine")
  g_eu <- g_eu + edge("Hungary","Romania")
  g_eu <- g_eu + edge("Hungary","Serbia")
  g_eu <- g_eu + edge("Hungary","Croatia")
  g_eu <- g_eu + edge("Hungary","Slovenia")
  g_eu <- g_eu + edge("Croatia","Slovenia")
  g_eu <- g_eu + edge("Croatia","Bosnia")
  g_eu <- g_eu + edge("Serbia","Bosnia")
  g_eu <- g_eu + edge("Romania","Ukraine")
  g_eu <- g_eu + edge("Serbia","Romania")
  g_eu <- g_eu + edge("Moldova","Ukraine")
  g_eu <- g_eu + edge("Moldova","Romania")
  g_eu <- g_eu + edge("Bulgaria","Romania")
  g_eu <- g_eu + edge("Bulgaria","Serbia")
  g_eu <- g_eu + edge("Bulgaria","Macedonia")
  g_eu <- g_eu + edge("Bulgaria","Greece")
  g_eu <- g_eu + edge("Bulgaria","Turkey")
  g_eu <- g_eu + edge("Greece","Turkey")
  g_eu <- g_eu + edge("Greece","Macedonia")
  g_eu <- g_eu + edge("Greece","Albania")
  g_eu <- g_eu + edge("Serbia","Macedonia")
  g_eu <- g_eu + edge("Serbia","Albania")
  g_eu <- g_eu + edge("Albania","Macedonia")
  
  #passer le graph en non dirigé
  g_eu <- as.undirected(g_eu, mode = c("collapse"))
  
  return(g_eu)
}